version: '3.8'

services:
  web:
    image: bejasadhev/fbihm-inventory:latest
    container_name: fbihm_web
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://74.208.174.70:27017/inventory_db
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - SECRET_KEY=supersecretkey
    restart: unless-stopped
    volumes:
      - ./static/uploads:/app/static/uploads
