name: Gitea Direct Stack Deploy

on:
  push:
    branches: [ "v2" ]

jobs:
  direct-deploy:
    runs-on: self-hosted # This MUST run on your server where the runner is installed
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Local Image
        run: |
          docker build -t fbihm-local:latest .

      - name: Initialize Swarm (If not already)
        run: |
          docker swarm init || true

      - name: Deploy Stack
        run: |
          # This deploys the stack using the locally built image
          docker stack deploy -c stack.yml fbihm_stack
          
      - name: Cleanup
        run: |
          docker system prune -f
