name: Docker Stack Auto Deploy

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Local Docker Image
        run: |
          docker build -t fbihm-local:latest .

      - name: Deploy to Swarm Stack
        run: |
          # Ensure Swarm is initialized
          docker swarm init || true
          # Deploy the stack using our stack.yml
          docker stack deploy -c stack.yml fbihm_stack

      - name: Cleanup Old Images
        run: |
          docker system prune -f
